---

- name: remove old ignition files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ocp_config_dir }}"
    - "{{ ocp_web_dir }}/master.ign"
    - "{{ ocp_web_dir }}/worker.ign"
    - "{{ ocp_web_dir }}/bootstrap.ign"
  when: "'ocp-mgmt' in group_names"

- name: Build the cluster directory
  file:
    path: "{{ ocp_config_dir }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  when: "'ocp-mgmt' in group_names"

- name: copy manifest to build directory
  command: "cp {{ ocp_config }} {{ ocp_config_dir }}"
  when: "'ocp-mgmt' in group_names"

- name: create ignition files
  command: "openshift-install create ignition-configs --dir=/mnt/arthur/rh/clusters/c1/{{ ansible_date_time.date }}"
  when: "'ocp-mgmt' in group_names"

- name: create ignition symlinks
  file:
    src: "{{ ocp_config_dir }}/{{ item }}"
    dest: "{{ ocp_web_dir }}/{{ item }}"
    state: link
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - master.ign
    - worker.ign
    - bootstrap.ign
  when: "'ocp-mgmt' in group_names"

- name: remove old kubeconfig
  file:
    path: /root/.kube/config
    state: absent
  when: "'ocp-mgmt' in group_names"

- name: make root .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  when: "'ocp-mgmt' in group_names"

- name: copy new kubeconfig to .kube
  command: "cp {{ ocp_config_dir }}/auth/kubeconfig /root/.kube/config"
  when: "'ocp-mgmt' in group_names"

#todo add OCP creds into
#- name: Add Credential Into Tower
#  tower_credential:
#    name: Workshop Credential
#    ssh_key_data: "{{ aws_ssh_key['content'] | b64decode }}"
#    kind: ssh
#    organization: Default
#    tower_username: admin
#    tower_password: ansible
#    tower_host: https://localhost
#  run_once: true
#  delegate_to: localhost

