---
- name: set ipmi next boot to network
  ipmi_boot:
    name: "{{ item }}"
    user: "{{ ipmi_username }}"
    password: "{{ ipmi_password }}"
    bootdev: network
    state: absent
  with_items:
    - fury-ipmi.h00pz.co
    - loki-ipmi.h00pz.co
    - yondu-ipmi.h00pz.co
