---
- name: set ipmi next boot to network
  ipmi_boot:
    name: "{{ item }}"
    user: '{{ lookup(env, "ANSIBLE_NET_USERNAME" }}'
    password: '{{ lookup(env, "ANSIBLE_NET_PASSWORD" }}'
    bootdev: network
    state: absent
  with_items:
    - fury-ipmi.h00pz.co
    - loki-ipmi.h00pz.co
    - yondu-ipmi.h00pz.co
